name = "agntlayer"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "AGNT_IDENTITY"
id = "99003c8b85454c3a8c5537fb37feccf3"

[[d1_databases]]
binding = "AGNT_DB"
database_name = "agnt-ledger"
database_id = "d2df3b3b-a510-4fb6-a1c8-a4b309e4d421"

[site]
bucket = "./public"
